-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgtfxSScLO1RcmxAQg
DgbcVEpuVjT/GxB/1q+c0i9e3YugCgYIKoZIzj0DAQehRANCAATcyJlazd2SVay3
YYjz60dwBr9AlSvbttIcXniqgl4OcxQCKgD7fb+K5pT3Lfo9nDJBpoofLeVc300X
lIVyZDQB
-----END PRIVATE KEY-----